categories:
  - title: '🚀 Added'
    label: 'added'
  - title: '🔧 Fixed'
    label: 'fixed'
  - title: '⬆️ Dependencies'
    label: 'dependencies'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes
  $CHANGES
