version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile.alpine-tmpl
    environment:
      - DEV=1
    ports:
      - "8000:80"
    volumes:
      - ./tasmoadmin:/var/www/tasmoadmin
