version: "3.9"
services:
  alpine-nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.alpine-tmpl
    ports:
      - "8000:80"
    environment:
      - TASMO_DATADIR=/data/tasmoadmin/
      - TASMO_DEBUG=1
    volumes:
      - ./tasmoadmin:/var/www/tasmoadmin
      - ./.storage:/data/tasmoadmin

  apache:
    build:
      context: .
      dockerfile: .docker/Dockerfile.apache
    ports:
      - "8001:80"
    environment:
      - TASMO_DATADIR=/data/tasmoadmin/
      - TASMO_DEBUG=1
    volumes:
      - ./tasmoadmin:/var/www/html
      - ./.storage:/data/tasmoadmin
