version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile.alpine-tmpl
    ports:
      - "8000:80"
    environment:
      - TASMO_DATADIR=/data/tasmoadmin/
    volumes:
      - ./tasmoadmin:/var/www/tasmoadmin
      - ./.storage:/data/tasmoadmin
