version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile.alpine-tmpl
    ports:
      - "8000:80"
    environment:
      - TASMO_DATADIR=/data/tasmoadmin/
      - TASMO_DEBUG=1
    volumes:
      - ./tasmoadmin:/var/www/tasmoadmin
      - ./.storage:/data/tasmoadmin


  apache:
    build:
      context: .
      dockerfile: .docker/Dockerfile.apache
    user: $USER_ID:$GROUP_ID
    ports:
      - "8001:80"
    environment:
      - TASMO_DEBUG=1
    volumes:
      - ./tasmoadmin:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
