FROM php:8.1-apache


RUN a2enmod rewrite

RUN apt-get update \
    && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

RUN mkdir -p /tmp/tasmoadmin/sessions \
    && chown -R www-data:www-data /tmp/tasmoadmin

# Expose
EXPOSE 80 443
