name: Release Beta

on:
  pull_request:
    types: [ labeled ]

jobs:
  release:
    if: ${{ github.event.label.name == 'release-beta' }}
    name: Release new beta version
    runs-on: ubuntu-20.04
    env:
      BUILD_REF: ${{ github.sha }}
      BUILD_VERSION: beta
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@master
    - name: Prepare
      run: |
        ./.docker/docker.sh prepare
    - name: Build docker images
      run: ./.docker/docker.sh build
    - name: Test docker images
      run: ./.docker/docker.sh test
    - name: Tag all docker images
      run: ./.docker/docker.sh tag
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push all docker images
      run: ./.docker/docker.sh push
    - name: Create and push manifest list
      run: ./.docker/docker.sh manifest-list
